### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by nickyoungforu** [aspuru-guzik-group/GA#1]
File "<string>", line 1, in <module>
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/opt/anaconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/opt/anaconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/Workspace/GA-master/core_GA.py", line 4, in <module>
    import discriminator as D
  File "/Users/Workspace/GA-master/discriminator.py", line 3, in <module>
    import evolution_functions as evo
  File "/Users/Workspace/GA-master/evolution_functions.py", line 15, in <module>
    manager = multiprocessing.Manager()
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "core_GA.py", line 4, in <module>
    import discriminator as D
  File "/Users/Workspace/repos/GA-master/discriminator.py", line 3, in <module>
    import evolution_functions as evo
  File "/Users/Workspace/GA-master/evolution_functions.py", line 15, in <module>
    manager = multiprocessing.Manager()
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/opt/anaconda3/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

env: python3.8

**Comment by akshat998** [comment]
Hi @nickyoungforu 

Sorry for the late response. I was wondering if you have tried running the code with Python3.6. 

This is what we used for the code. It might be that the latest version of python is causing some environment error :)

**Comment by nickyoungforu** [comment]
> Hi @nickyoungforu
> 
> Sorry for the late response. I was wondering if you have tried running the code with Python3.6.
> 
> This is what we used for the code. It might be that the latest version of python is causing some environment error :)

thanks
