### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (500,1) (0,1) 

### ISSUE THREAD

**Issue by schithranandanurix** [aspuru-guzik-group/GA#2]
Hi all,

When I run the core_GA script with a list of 6 starting SELFiES, I appear to be running into a numpy operator issue when it tries to compute the fitness using the normalized values of logP, SAS and RingP. Was wondering if anyone ever ran into this before and whether it's an issue with my starting dataset or a newer version of a dependency?

```
   ###   On generation 1 of 200
Traceback (most recent call last):
  File "core_GA.py", line 130, in <module>
    impose_time_adapted_pen    = False
  File "core_GA.py", line 55, in initiate_ga
    image_dir,          data_dir,      max_fitness_collector, impose_time_adapted_pen)
  File "/nfshomes/schithrananda/generative_ml_experiments/GA/generation_props.py", line 296, in obtain_fitness
    disc_enc_type, generation_index,   max_molecules_len, device, num_processors, writer, beta, data_dir, max_fitness_collector, impose_time_adapted_pen) 
  File "/nfshomes/schithrananda/generative_ml_experiments/GA/generation_props.py", line 164, in fitness
    fitness = (logP_norm) - (SAS_norm) - (RingP_norm)
ValueError: operands could not be broadcast together with shapes (500,1) (0,1) 
```

Beyond modifying the starting_selfies to use a custom one rather than a sample of ZINC - these are the settings I used:

```
            # Initiate the Genetic Algorithm
            smiles_all_counter = initiate_ga(    num_generations            = 200,
                                                 generation_size            = 500,
                                                 starting_selfies           = selfies_list, # pass reference selfies
                                                 max_molecules_len          = 100, #changed to 100
                                                 disc_epochs_per_generation = 10,
                                                 disc_enc_type              = 'properties_rdkit',         # 'selfies' or 'smiles' or 'properties_rdkit'
                                                 disc_layers                = [100, 10],
                                                 training_start_gen         = 0,                          # generation index to start training discriminator
                                                 device                     = 'cpu',
                                                 # pass all penalties for now since I want to see ring size, synthesizability, drug-likeness and logP
                                                 properties_calc_ls         = ['logP', 'SAS', 'QED' 'RingP'],   # None: No properties ; 'logP', 'SAS', 'RingP', 'QED'
                                                 num_processors             = multiprocessing.cpu_count(),
                                                 beta                       = beta,
                                                 max_fitness_collector      = max_fitness_collector,
                                                 impose_time_adapted_pen    = True
                                            )
            

```

**Comment by schithranandanurix** [comment]
This was solved by increasing the size of starting selfies to be 500 (by duplicating the SMILES strings. Closing this issue, thanks!
